defaults:
  - default

_target_: pbtrack.wrappers.Dartfish

dataset_path: ${data_dir}
annotation_path: ${data_dir}/dartfish_trackdata_tracklets_2kp_allpeople

nvid: -1                                    # -1 -> process all the videos
nframes: -1                                 # -1 -> process all the frames by video

vids_dict:                                  # video names to use for each train/val/test set
  train: []
  val: []  # leave empty to use all videos
  test: []