_target_: inference.AFLinkWrapper


cfg:
  checkpoint: dartfishmodel_epoch100.pth
  root_train: '/work/vita/datasets/Dartfish/Track_Data/annotations_linked_by_video'
  download_weights: "aoBb1vVP3oNxhohJQr_YhsyYZpMP3ko-"
  download_type: "drive"
  path_to_checkpoint: ${checkpoints_dir} 

  train_batch:  16
  train_epoch: 100
  train_lr: 0.001
  #train_lr = 0.0001
  train_warm: 0
  train_decay: 0.00001
  num_workers: 0
  val_batch: 32
  model_minLen: 30
  model_inputLen: 30
  thrP: 0.05
  thrS: 200
  thrT_max: 30
  thrT_min: 0
  dir_out: None
  path_in: ${checkpoints_dir} 



