_target_: inference.Yolov5Wrapper

cfg:
  download_weights: "1r2gMCCHWUBJwh5WrKw15CdNTob6cce4h"
  download_type: "drive"
  path_to_checkpoint: ${checkpoints_dir} 
  checkpoint: 'last.pt' # yolov8x-pose-p6.pt # 
  min_confidence: 0
  conf : 0.25  # NMS confidence threshold
  iou : 0.45  # NMS IoU threshold
  agnostic : False  # NMS class-agnostic
  multi_label : False  # NMS multiple labels per box
  max_det : 1000  # maximum number of detections per image
  read_video : True
